#!/usr/bin/env bash
# notify.sh — surface Claude Code hook events as desktop notifications.
#
# Wired in `.claude/settings.json` against: Notification, Stop, TaskCompleted.
# Reads JSON from stdin per Claude Code hook protocol.
#
# Cross-platform: macOS uses osascript, Linux uses notify-send when available.
# Falls back to writing to /tmp/<team>-hooks.log on unknown events / unsupported OS.
#
# Generated by agents-team `/team-gen`. The {{TEAM_NAME}} token is replaced
# at generation time; if you copied this manually, replace it yourself.

set -u

TEAM_NAME="{{TEAM_NAME}}"
LOG_FILE="/tmp/${TEAM_NAME,,}-hooks.log"

INPUT=$(cat)
EVENT_TYPE=$(echo "$INPUT" | jq -r '.event_type // .type // "unknown"')

notify() {
  local title="$1"
  local body="$2"
  local sound="${3:-Glass}"

  case "$(uname -s)" in
    Darwin)
      osascript -e "display notification \"${body}\" with title \"${title}\" sound name \"${sound}\""
      ;;
    Linux)
      if command -v notify-send >/dev/null 2>&1; then
        notify-send "$title" "$body"
      else
        echo "[notify] $(date -u +%Y-%m-%dT%H:%M:%SZ) $title: $body" >> "$LOG_FILE"
      fi
      ;;
    *)
      echo "[notify] $(date -u +%Y-%m-%dT%H:%M:%SZ) $title: $body" >> "$LOG_FILE"
      ;;
  esac
}

case "$EVENT_TYPE" in
  Notification)
    MESSAGE=$(echo "$INPUT" | jq -r ".message // \"${TEAM_NAME} needs your attention\"")
    TITLE=$(echo "$INPUT"   | jq -r ".title // \"${TEAM_NAME}\"")
    notify "$TITLE" "$MESSAGE" "Glass"
    ;;
  Stop)
    SESSION=$(echo "$INPUT" | jq -r '.session_id // ""')
    body="Session ended"
    [[ -n "$SESSION" ]] && body="Session ${SESSION} ended"
    notify "$TEAM_NAME" "$body" "Purr"
    ;;
  TaskCompleted)
    TASK=$(echo "$INPUT"  | jq -r '.task_subject // .task_title // "Task"')
    AGENT=$(echo "$INPUT" | jq -r '.teammate_name // .agent_type // ""')
    body="${TASK} completed"
    [[ -n "$AGENT" ]] && body="${TASK} — completed by ${AGENT}"
    notify "$TEAM_NAME" "$body" "Glass"
    ;;
  *)
    echo "[notify] $(date -u +%Y-%m-%dT%H:%M:%SZ) event=${EVENT_TYPE} data=${INPUT}" >> "$LOG_FILE"
    ;;
esac
